# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

#pod 'evernote-cloud-sdk-ios', :git => 'https://github.com/evernote/evernote-cloud-sdk-ios.git', :branch => 'ios7'
pod 'evernote-cloud-sdk-ios', '2.0.2'
pod 'UMengAnalytics', '3.5.10'
pod 'UMengSocial', '4.2.3'
pod 'MBProgressHUD', '0.9'
pod 'TTTAttributedLabel', '1.10.1'
pod 'RegexKitLite-NoWarning', '1.1.0'
pod 'hpple', '0.2.0'
pod 'POP+MCAnimate', '2.0.1'
pod 'SDWebImage', '~>3.7'
pod 'JazzHands', '2.0.0'
pod 'Masonry', '0.5.3'  #新特性动画
#pod 'YYKit', '~> 0.9.7'
pod 'Bugly','1.4.3'
pod 'MJExtension', '~> 3.0.7'

#pod 'TPKeyboardAvoiding', '1.2.4'
#pod 'BlocksKit', '2.2.5'
#pod 'ReactiveCocoa', '2.3.1'
#pod 'MMMarkdown', '0.3'
#pod 'NYXImagesKit', '2.3'
#pod 'UIImage+BlurredFrame', '0.0.4'
#pod 'PPiAwesomeButton'
#pod 'APParallaxHeader'
#pod 'SDCAlertView', '2.5.2'
#pod 'MarqueeLabel'
#pod 'TMCache', '2.1.0'     #对iOS和OS X对象快速并行的缓存
#pod 'iVersion', '1.11.4'   #检测更新
#pod 'SSKeychain', '1.2.3'  #轻量级iOS安全框架



target 'TFWeibo' do

end

target 'TFWeiboTests' do

end

target 'TFWeiboUITests' do

end

